string(TIMESTAMP LIB_VERSION_DATE %Y-%m-%d)
string(TIMESTAMP LIB_VERSION_TIME %H:%M:%S)

#configure_file(${FROM_FILE} ${TO_FILE})

FILE(WRITE ${TO_FILE}

"/* *DO*NOT*EDIT* - generated by CMake */ \n"
"\n"
"#define LIB_VERSION      \"${LIB_VERSION}\"\n"
"#define LIB_CM_VERSION   \"${LIB_CM_VERSION}\"\n"
"#define LIB_VERSION_DATE \"${LIB_VERSION_DATE}\"\n"
"#define LIB_VERSION_TIME \"${LIB_VERSION_TIME}\"\n"
"#define LIB_ARCH         \"${LIB_ARCH}\"\n"
"#define LIB_CFLAGS       \"${LIB_CFLAGS}\"\n"

)
